#!/usr/bin/env python3
"""Generate (or verify) the donor checkout manifest from donor profiles.

Each donor profile under references/donor-library/profiles/ declares its
upstream in a leading "Source: <url>" line. This tool extracts every profile's
primary git source into a TSV manifest (profile-name<TAB>clone-url) consumed by
scripts/fetch_donor_checkouts.sh, so users of the public repo can materialize
donor checkouts locally instead of hand-copying URLs out of markdown.

Non-git sources (vendor pages, papers) are skipped with a note; profiles whose
Source line is missing are reported. --check verifies the committed manifest
matches the profiles (used by validate.sh to prevent drift).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

GIT_HOST_PATTERN = re.compile(
    r"^https://(github\.com|gitlab\.com|gitlab\.freedesktop\.org|gitea\.com|"
    r"codeberg\.org|bitbucket\.org)/[^\s)]+", re.IGNORECASE)
SOURCE_PATTERN = re.compile(r"^Source:\s*(\S+)\s*$", re.MULTILINE)


def extract_entries(profiles_dir: Path) -> tuple[list[tuple[str, str]], list[str]]:
    entries: list[tuple[str, str]] = []
    skipped: list[str] = []
    for profile in sorted(profiles_dir.glob("*.md")):
        text = profile.read_text(encoding="utf-8")
        match = SOURCE_PATTERN.search(text)
        if match is None:
            skipped.append(f"{profile.name}: no Source line")
            continue
        url = match.group(1).rstrip("/").removesuffix(".git")
        if GIT_HOST_PATTERN.match(url) is None:
            skipped.append(f"{profile.name}: non-git source {url}")
            continue
        entries.append((profile.stem, url + ".git"))
    return entries, skipped


def render(entries: list[tuple[str, str]]) -> str:
    lines = [
        "# Generated by scripts/generate_donor_checkout_manifest.py - do not edit by hand.",
        "# profile-name<TAB>clone-url (donor checkouts are reference-only; respect each license)",
    ]
    lines += [f"{name}\t{url}" for name, url in entries]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo_root", nargs="?", default=".", type=Path)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed manifest matches the profiles")
    args = parser.parse_args()

    library = args.repo_root / "skills/cpp-cuda-vulkan-studio/references/donor-library"
    profiles_dir = library / "profiles"
    manifest_path = library / "donor-checkouts.manifest"
    if not profiles_dir.is_dir():
        print(f"error: profiles directory not found: {profiles_dir}", file=sys.stderr)
        return 2

    entries, skipped = extract_entries(profiles_dir)
    rendered = render(entries)
    for note in skipped:
        print(f"note: skipped {note}")

    if args.check:
        if not manifest_path.exists():
            print(f"error: manifest missing: {manifest_path}", file=sys.stderr)
            return 1
        if manifest_path.read_text(encoding="utf-8") != rendered:
            print("error: donor-checkouts.manifest is out of date; run "
                  "scripts/generate_donor_checkout_manifest.py", file=sys.stderr)
            return 1
        print(f"donor checkout manifest OK ({len(entries)} donors)")
        return 0

    manifest_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {manifest_path} ({len(entries)} donors, {len(skipped)} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
